theme: jekyll-theme-minimal
title: Oracle des Premiers Principes
description: L'Oracle des Premiers Principes est un outil de réflexion personnel qui s'inspire de la démarche scientifique et philosophique du raisonnement par premiers principes.
